### ISSUE TITLE
注文入力画面を作る

### ISSUE THREAD

**Issue by k-okajima** [its-succ/bento#15]

**Comment by Rika-Yoshimura** [comment]
その他、実装したいと思ってること

- 日付ごとの金額欄、1週間分の合計の表示を追加する。
- SELECT部品の選択内容により金額と合計の表示を変更する。
- ごはんつきのおかずを選んだ場合、ごはんは強制的に未選択とする（disabledとかにはしないでおく）
- 〆られた状態かどうかを考慮する（修正可・不可）

**Comment by Rika-Yoshimura** [comment]
ほぼ実装できたかな～と思うので完了とします。
