### ISSUE TITLE
データストアにエンティティを作成する

### ISSUE THREAD

**Issue by Rika-Yoshimura** [its-succ/bento#30]
マスタ.okazu, gohan のエンティティを作成しました。
注文は過去履歴を数件ダミー登録する。

**Comment by Rika-Yoshimura** [comment]
注文(Order）の過去履歴として3件ほど登録しました。
テストで必要なデータがあればｆ、各自登録お願いします。
このタスク自体は終了します。

**Comment by sakai-y** [comment]
> 注文(Order）の過去履歴として3件ほど登録しました。

どこに・・・？
