### ISSUE TITLE
モデルを設計する

### ISSUE THREAD

**Issue by esm-watanabe** [its-succ/bento#5]
![image](https://user-images.githubusercontent.com/29788946/30998000-8083b458-a506-11e7-8c23-82c9b2152e89.png)

**Comment by sakai-y** [comment]
## 永続化データ
### 注文
- ユーザID
- 日付
- おかずの種類（'ai'とか？）
- ごはんの種類（'normal'とか？）
- 味噌汁有無

・・・あれ？これだけでいけちゃう？

**Comment by sakai-y** [comment]
### マスタ
- おかずマスタ
  - 種類／金額
- ごはんマスタ
  - 種類／金額

**Comment by k-okajima** [comment]
静的ファイル（献立表）をデータストアにぶち込むことになるかもしれない。

**Comment by Rika-Yoshimura** [comment]
マスタは、画面表示用に日本語名称（「愛」「ゆうき」）もほしいです。
「種類」はaiとか一意の値であればよいです。
