### ISSUE TITLE
モックを作る

### ISSUE THREAD

**Issue by Rika-Yoshimura** [its-succ/bento#7]
pingendo 使ってまず画面イメージ決める。
・ログイン画面
・注文画面
・閲覧画面
あたりは作ろう。

スマホからも見れる画面レイアウトにする。

**Comment by Rika-Yoshimura** [comment]
ログイン画面と注文画面のモックは作成しました。

注文画面について、「来週いりません」の意思表示がいるかと思ってモックでは「いりません」ボタンをつけてみてます。
漆崎さんが「いるのかいらないのか」が知りたいはず。
機能的にどう実現するかは課題。

**Comment by esm-watanabe** [comment]
管理部の注文確認画面に金額合計がほしい

**Comment by esm-watanabe** [comment]
管理部の注文確認画面のサマリは、ごはん、味噌汁はまとめてよい
（おかず毎にごはんが変わるわけではない。全体としてごはんの種類ごとの個数があるとよい）

**Comment by esm-watanabe** [comment]
個人の履歴参照画面は漆崎さんも見れるようにしたい。
個人ごとの合計はそこで見る

**Comment by esm-watanabe** [comment]
締めを行ったら、翌週のカレンダーの表示。
翌週と締めた週（今週分）が参照したい

**Comment by esm-watanabe** [comment]
管理部のみ、個人の履歴参照画面で人を選べるようにしたい。
頼んだ人のリスト

**Comment by esm-watanabe** [comment]
締めるまでなら、個人の入力画面で自由に修正してよい
ランチメニューは締めると同時に翌週分をアップ
おかずで応援弁当が選ばれたら必然的にごはんなしでロックできないか。（勝手にごはんが付く）
今週いりませんのボタンを押したら、管理部履歴画面上は表示されないが個人履歴画面に「いりません」の表示

**Comment by esm-watanabe** [comment]
カレンダーは、いずれ、できたら、グーグルカレンダーで休日が分かるといい

**Comment by Rika-Yoshimura** [comment]
実装に入るのでこちらクローズします。
モック修正がある画面は各自のブランチで続きをお願いします。
